-- AlterTable
ALTER TABLE "courses" ALTER COLUMN "created_at" SET DATA TYPE DATE,
ALTER COLUMN "updated_at" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "enrollments" ALTER COLUMN "created_at" SET DATA TYPE DATE,
ALTER COLUMN "updated_at" SET DATA TYPE DATE,
ALTER COLUMN "deleted_at" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "lessons" ALTER COLUMN "created_at" SET DATA TYPE DATE,
ALTER COLUMN "updated_at" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "modules" ALTER COLUMN "created_at" SET DATA TYPE DATE,
ALTER COLUMN "updated_at" SET DATA TYPE DATE;

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "birth_date" SET DATA TYPE DATE,
ALTER COLUMN "created_at" SET DATA TYPE DATE,
ALTER COLUMN "updated_at" SET DATA TYPE DATE;
