// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package database

import "gorm.io/gorm"

type Course struct {
	gorm.Model
	ID            string        `json:"id"`
	Title         string        `json:"title"`
	Slug          string        `gorm:"index:,unique"`
	Description   *string       `json:"description"`
	CreatedAt     string        `json:"created_at"`
	UpdatedAt     *string       `json:"updated_at"`

}

type Enrollment struct {
	gorm.Model
	ID       string    `gorm:"index:,unique"`
	UserID   string    `json:"user_id"`
	CourseID string    `json:"course_id"`

}

type Lesson struct {
	gorm.Model
	ID     string    `json:"id"`
	Title  string    `json:"title"`
	Slug   string    `gorm:"index:,unique"`
	Link   *string   `json:"link"`

}

type Module struct {
	gorm.Model
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Slug        string    `gorm:"index:,unique"`

}

type NewCourse struct {
	ID            string    `json:"id"`
	Title         string    `json:"title"`
	Slug          string    `json:"slug"`
	Description   *string   `json:"description"`
	CreatedAt     string    `json:"created_at"`
	UpdatedAt     *string   `json:"updated_at"`
	AuthorID      []*string `gorm:"foreignKey:ID;references:ID"`
	EnrollmentsID []*string `gorm:"foreignKey:ID;references:ID"`
	ModulesID     []*string `gorm:"foreignKey:ID;references:ID"`
}

type NewEnrollment struct {
	ID       string    `json:"id"`
	UserID   []*string `json:"user_id"`
	CourseID []*string `json:"course_id"`
}

type NewLesson struct {
	ID       string    `json:"id"`
	Title    string    `json:"title"`
	Slug     string    `json:"slug"`
	Link     string    `json:"link"`
	ModuleID []*string `json:"module_id"`
	CourseID []*string `json:"course_id"`
}

type NewModule struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Slug        string    `json:"slug"`
	LessonsID   []*string `json:"lessons_id"`
	CourseID    []*string `json:"course_id"`
}

type NewUser struct {
	ID        *string `json:"id"`
	Firstname string  `json:"firstname"`
	Lastname  string  `json:"lastname"`
	Email     string  `gorm:"index:,unique"`
	Password  string  `json:"password"`
	Cellphone string  `gorm:"index:,unique"`
	BirthDate *string `json:"birth_date"`
	TokenUser *string `json:"token_user"`
}

type User struct {
	gorm.Model
	ID          string        `json:"id"`
	Firstname   string        `json:"firstname"`
	Lastname    string        `json:"lastname"`
	Email       string        `json:"email"`
	Password    string        `json:"password"`
	Cellphone   string        `json:"cellphone"`
	BirthDate   string       `json:"birth_date"`
	TokenUser   string       `json:"token_user"`
}
